Fixed python install step

diff --git a/.github/workflows/cve_pipeline.yml b/.github/workflows/cve_pipeline.yml
--- a/.github/workflows/cve_pipeline.yml
+++ b/.github/workflows/cve_pipeline.yml
@@ -36,7 +36,7 @@ jobs:
           with: 
             python-version: 3.9
             cache: 'pip'
-            run:
+            run: |
                 python -m pip install --upgrade pip
                 pip install -r requirements.txt
 
@@ -56,4 +56,28 @@ jobs:
             echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
             #Setting directory permissions to r+w only 
             chmod 600 ~/.kaggle/kaggle.json
+
+        # Step 5: Run cve extraction and csv creation from vulnerichment repo
+        - name: Run CVE extraction from CISA vulnrichment repository
+          run: |
+            # First, check if GITHUB_TOKEN is set
+            if [ -n "${{ secrets.GITHUB_TOKEN }}" ]; then
+              echo "GITHUB_TOKEN is set"
+            else
+              echo "GITHUB_TOKEN is not set"
+            fi
+
+            #Second, check if Kaggle credential env variables are set
+            if [ -n "${{ secrets.KAGGLE_USERNAME }}" ] && [ -n "${{ secrets.KAGGLE_KEY }}" ]; then
+              echo "Kaggle credentials are set"
+            else
+              echo "Kaggle credentials are not set"
+            fi
+
+            # Third, start CVE extraction
+            echo 'Starting CVE extraction...'
+            python extract2.py
+            echo 'CVE extraction completed.'
+
+            [ -f "cve_data.csv" ] && echo " CSV file created successfully." || echo "Failed to create output CSV file."
 
